describe( 'state/chatlist/reducer', () => {
	it( 'INSERT_NEW_CHAT' );
	it( 'INSERT_PENDING_CHAT' );
	it( 'SET_CHAT_OPERATOR' );
	it( 'SET_OPERATOR_CHATS_ABANDONED' );
	it( 'SET_CHATS_RECOVERED' );
	it( 'SET_CHAT_CUSTOMER_DISCONNECT' );
	it( 'ASSIGN_CHAT' );
	it( 'SET_CHAT_MISSED' );
	it( 'CLOSE_CHAT' );
	it( 'AUTOCLOSE_CHAT' );
	it( 'OPERATOR_JOIN' );
	it( 'SET_USER_OFFLINE' );
	it( 'REMOVE_USER' );
	it( 'OPERATOR_CHAT_LEAVE' );
	it( 'OPERATOR_CHAT_JOIN' );
	it( 'OPERATOR_CHAT_TRANSFER' );
	it( 'UPDATE_CHAT' );
	it( 'REMOVE_CHAT' );
	it( 'SERIALIZE' );
} );
